image: fedora:23

before_script:
  - 'dnf -y update'
  - 'dnf install -y salt-minion'
  - 'salt-call state.sls basebox --local --file-root ./salt/roots'
  - './autogen.sh'
  - 'mkdir build'
  - 'cd build && ../configure'

unit_tests:
  script:
    - 'make'
