dist: trusty
language: cpp
sudo: required

addons:
  apt:
    packages:
    - clang-format-4.0
    sources:
    - llvm-toolchain-trusty-4.0
    - ubuntu-toolchain-r-test

script:
- find . -regex '.*\.\(hh?\|cc?\|hpp\|cpp\)$' | xargs clang-format-4.0 -i -style=file -fallback-style=llvm
- git diff --exit-code

branches:
  only:
  - master
